### ISSUE TITLE
input file format

### ISSUE THREAD

**Issue by neko-ni** [rraadd88/beditor#14]
I am confuse when supporting the tsv input file. I try to use the example file for S. cerevisiae . I am not sure what's the form of genome coordinate.So i just use the first two rows of the example.But it can't go well. Is that a bug or something? 
##########
Namespace(cfg=None, force=False, step=None, test=False)
Traceback (most recent call last):
  File "/public1/users/sunmw/miniconda3/envs/beditor/bin/beditor", line 8, in <module>
    sys.exit(main())
  File "/public1/users/sunmw/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 465, in main
    gui(test=args.test)
  File "/public1/users/sunmw/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/gui.py", line 552, in gui
    din=din.rename(columns={c:normalised2cols[normalisestr(c)] for c in din})
  File "/public1/users/sunmw/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/gui.py", line 552, in <dictcomp>
    din=din.rename(columns={c:normalised2cols[normalisestr(c)] for c in din})
KeyError: 'i147494147494'
####################
tsv file is like:
I:147494-147494-	A
I:143607-143607+	A
Is there something I do wrong? Thanks a lot!
@rraadd88

**Comment by rraadd88** [comment]
Hi @neko-ni,
Could you please try the command-line mode and see if you get the same error?
Also, for your trial and specifically for the format of input file, you could try this example [file](https://github.com/rraadd88/test_beditor/blob/master/dataset_saccharomyces_cerevisiae_release95/input_nucleotide.tsv)?
Please let me know if that works. I will be able to troubleshoot the issue accordingly.
