### ISSUE TITLE
error occur when run human species test_dataset 

### ISSUE THREAD

**Issue by yxian9** [rraadd88/beditor#2]
Hi, 

The beditor is really helpful!  Would you please take a look on one error which occured when I run the test dataset?

First of all, The `test_datasets.py` run perfectly. I assumed the software has been successfully installed on our server. 

Then when I try `make_datasets.py` , and use `source activate beditor;cd test_beditor/dataset_homo_sapiens; beditor --cfg mutation_format_nucleotide_mutation_mutations_for.yml`. I get the error as following:

> logfile: .log_beditor_2018_10_11_13_20_33_179487_mutation_format_nucleotide_mutation_mutations_for.yml_None_None_False_False.log
2018_10_11_13_20_35_241797: processing: mutation_format_nucleotide_mutation_mutations_for
2018_10_11_13_20_36_760623: processing: 5 chunks.
2018_10_11_13_20_36_829145: processing: chunk00000003
2018_10_11_13_20_36_834763: processing: chunk00000001
2018_10_11_13_20_36_829236: processing: chunk00000004
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 106, in pipeline_chunks
    dguides2offtargets(cfg)
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/lib/get_specificity.py", line 465, in dguides2offtargets
    cfg=dannots2dalignbed2dannotsagg(cfg)
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/lib/get_specificity.py", line 281, in dannots2dalignbed2dannotsagg
    to_colns=['gene name','gene id','transcript id','protein id','exon id'])
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/lib/io_dfs.py", line 196, in lambda2cols
    axis=1).apply(pd.Series)
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/frame.py", line 6014, in apply
    return op.get_result()
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/apply.py", line 142, in get_result
    return self.apply_standard()
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/apply.py", line 248, in apply_standard
    self.apply_series_generator()
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/apply.py", line 277, in apply_series_generator
    results[i] = self.f(v)
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/lib/io_dfs.py", line 195, in <lambda>
    df_=df.apply(lambda x: lambdaf(x[in_coln]),
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/lib/io_seqs.py", line 105, in gffatributes2ids
    if '=' in s:
TypeError: ("argument of type 'float' is not iterable", 'occurred at index 1|+120558086|22M|2')
"""

> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/bin/beditor", line 11, in <module>
>     sys.exit(main())
>   File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 491, in main
>     test=args.test,force=args.force)
>   File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 425, in pipeline
>     pool.map(pipeline_chunks, chunkcfgps)
>   File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 266, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
> TypeError: ("argument of type 'float' is not iterable", 'occurred at index 1|+120558086|22M|2')
> (beditor)

Similar error also show when test danio_rerio species:
```
> The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/bin/beditor", line 11, in <module>
    sys.exit(main())
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 491, in main
    test=args.test,force=args.force)
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 425, in pipeline
    pool.map(pipeline_chunks, chunkcfgps)
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/mnt/silencer2/home/ydiao/Oct4/Software/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: ("argument of type 'float' is not iterable", 'occurred at index 1|-16522189|22M|2')
(beditor)
```

Thank you very much!

**Comment by rraadd88** [comment]
Hello @yuxuth ,
That is strange! Could you try the newest version of from git repo?
Also can you post the `mutation_format_nucleotide_mutation_mutations_for.yml` file.
Thanks.

**Comment by yxian9** [comment]
Hi @rraadd88 ,

Thank you for replying me!  The beditor version I used is v1.1.1. I installed it using `pip install beditor`, following your installation manual.  Is there a new version on git repo? I will try to install directly from git repo

The `mutation_format_nucleotide_mutation_mutations_for.yml` file is generated by `make_datasets.py`. I also post it here:
```
BEs:
- Target-AID
- ABE
chunksize: 200
cores: 6
dinp: input_nucleotide.tsv
dsubmap_preferred_path: null
genomeassembly: GRCh38
genomerelease: 92
host: homo_sapiens
max_subs_per_codon: 1
mimetism_level: medium
mutation_format: nucleotide
mutations: mutations
pams:
- NGG
- NG 
```

**Comment by rraadd88** [comment]
Hi again @yuxuth ,
Just curious to whether you tried the updated version (either from git or pypi (currently 1.1.3)). 
Also make sure that pyensembl (1.6.0) and other dependencies are installed through the conda-virtual-environment file as follows:
```
wget https://raw.githubusercontent.com/rraadd88/beditor/master/environment.yml
conda env create -f environment.yml
```

**Comment by yxian9** [comment]
It works on the latest version v1.1.3.  Thank you very much!

**Comment by rraadd88** [comment]
You are welcome!
