### ISSUE TITLE
Custom PAM

### ISSUE THREAD

**Issue by bioinfo4321** [rraadd88/beditor#9]
Hi, I am not able to make beditor run with any PAM other than NG and NGG, for example, i tried NGA and got following error. Same configuration runs perfectly fine for NGG. Thanks for your response.

_ multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'nucleotide mutation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 106, in pipeline_chunks
    dseq2dmutagenesis(cfg)
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/lib/get_mutations.py", line 341, in dseq2dmutagenesis
    host=cfg['host'])
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/lib/get_mutations.py", line 171, in get_possible_mutagenesis
    dmutagenesis['nucleotide mutation: count']=[len(s) for s in dmutagenesis['nucleotide mutation']]  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'nucleotide mutation'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda/envs/beditor/bin/beditor", line 10, in <module>
    sys.exit(main())
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 461, in main
    test=args.test,force=args.force)
  File "/home/user/miniconda/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 405, in pipeline
    pool.map(pipeline_chunks, chunkcfgps)
  File "/home/user/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/user/miniconda/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: 'nucleotide mutation'
  _

**Comment by bioinfo4321** [comment]
issue seems to resolve by appropriately editing provided dbepams.tsv, issue closed.
